# **Encoding Categorical Variables**

In machine learning, **Encoding** is the process of converting categorical data (text-based labels like "Red," "Green," or "Large") into **numerical values**.

#### **Why do we need it?**
Most machine learning algorithms are based on mathematical equations. Since you cannot perform math on a string of text, we must translate those labels into numbers so the model can process the features and find patterns.

#### **The Core Goal**
The objective is to represent the data numerically while preserving its meaning. We want to ensure the model understands:
* Whether the categories have a specific **rank/order** (Ordinal).
* Whether the categories are **independent** of each other (Nominal).

---

## 1. Label Encoding

Converts categorical values into numbers while preserving order.

**When to use:**
Use when data has a natural order (ordinal data).

**Dataset used:**
Students Performance in Exams Kaggle dataset
https://www.kaggle.com/code/pragya1110/student-performance-in-exam?select=StudentsPerformance.csv

**Column:**
parental level of education

**Why use here:**
This column has order (high school < ... < master’s), so label encoding keeps this ranking, helping the model understand progression.

**Example:**
high school → 0, …, master’s → 4

### Load Dataset

In [1]:
import pandas as pd
df = pd.read_csv("StudentsPerformance.csv")

### Read first five rows

In [2]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Find unique value in parental level of education

In [3]:
df["parental level of education"].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

### Do label encoding bases on education level

In [4]:
education_order = [
    "some high school",
    "high school",
    "some college",
    "associate's degree",
    "bachelor's degree",
    "master's degree"
]

mapping = {k: i for i, k in enumerate(education_order)}

df["parent_edu_encoded"] = df["parental level of education"].map(mapping)

print(df[["parental level of education", "parent_edu_encoded"]].head())

  parental level of education  parent_edu_encoded
0           bachelor's degree                   4
1                some college                   2
2             master's degree                   5
3          associate's degree                   3
4                some college                   2

## 2. One-Hot Encoding

Used when there is no order between categories (nominal data).

**When to use:**
Use when categorical values are independent and have no ranking.

**Dataset used:**
Seaborn Titanic dataset

**Column:**
Embarked

**Why use here:**
Embarked has categories (C, Q, S) with no order or priority. So One-Hot Encoding is used to avoid false ranking that would happen in label encoding.

**Example:**
C → [1,0,0]

Q → [0,1,0]

S → [0,0,1]

### Load dataset

In [5]:
import seaborn as sns
df = sns.load_dataset("titanic")

### Read first five rows

In [6]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Do One-Hot encoding

In [7]:
df_encoded = pd.get_dummies(df, columns=["embarked"], drop_first=False)
print(df_encoded[["embarked_C", "embarked_Q", "embarked_S"]].head())

   embarked_C  embarked_Q  embarked_S
0       False       False        True
1        True       False       False
2       False       False        True
3       False       False        True
4       False       False        True

## 3. Target Encoding

Replace each category with the mean of the target variable for that category.

**When to use:**
Use when categorical variable has strong relationship with the target and high cardinality.

**Dataset used:**
Titanic dataset

**Column:**
Embarked

**Why use here:**
Embarked categories (C, Q, S) are replaced with the mean survival rate of each group. This helps the model capture the relationship between boarding location and survival.

**Example:**
C → mean survival of C passengers
Q → mean survival of Q passengers
S → mean survival of S passengers

### Load dataset

In [8]:
import seaborn as sns
df = sns.load_dataset("titanic")

### Read first five rows

In [9]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Do target encoding

In [10]:
target_mean = df.groupby("embarked")["survived"].mean()
df["embarked_target_encoded"] = df["embarked"].map(target_mean)
print(df[["embarked", "embarked_target_encoded"]].head())

  embarked  embarked_target_encoded
0        S                 0.336957
1        C                 0.553571
2        S                 0.336957
3        S                 0.336957
4        S                 0.336957