# Handling Missing Values

Missing values are common in real-world datasets. Handling them properly is important because most machine learning algorithms cannot handle `NaN` or empty values directly.

## Why Handle Missing Values?
- Prevent errors during model training.
- Avoid biased or inaccurate results.
- Improve model performance and reliability.

## Common Strategies
1. **Removing missing values**  
   - Drop rows or columns containing missing data.  
   - Useful when missing data is small or irrelevant.

2. **Imputation**  
   - Fill missing values using:  
     - **Mean / Median / Mode** for numerical data.  
     - **Most frequent / constant** for categorical data.  
   - Preserves dataset size.

3. **Prediction-based methods**  
   - Predict missing values using other features.  
   - Advanced but more accurate.

4. **Flagging missing values**  
   - Create a new column to indicate missing values.  
   - Helps model learn patterns related to missing data.

**Use Case:** This is used in **data cleaning, preprocessing, and preparation** before feeding data into any ML model.

---

## Dataset Used

We are using the Titanic dataset available in seaborn

This dataset contains information about passengers such as age, gender, class, and whether they survived or not.

In [1]:
import seaborn as sns
df = sns.load_dataset("titanic")

---

# 1. Checking for missing value

## inspect missing data

In [2]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### Explanation
- `df.isnull().sum()` counts the missing values (`NaN`) in each column.  
- Columns like `age`, `deck`, and `embarked` have missing values.  
- Columns with `0` missing values are complete and do not need handling.  

### Use for
- Use this method to **quickly inspect missing data** in any dataset before deciding on imputation or removal strategies.

---

## checking missing values as percentage

In [3]:
df.isnull().mean() * 100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

### Explanation
- `df.isnull().mean() * 100` calculates the **percentage of missing values** for each column.  
- `age` has ~20% missing values, `deck` has ~77%, while columns like `survived` have 0%.  
- High missing percentage (like `deck`) may need careful handling; sometimes dropping the column is better.  

### Use for
- Use this method to **prioritize columns for imputation or removal** based on how much data is missing.

---

# 2. Handling missing value

## Dropping Columns with High Missing Values

In [4]:
df.drop(columns=["deck"])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

Sometimes, columns with a very high percentage of missing data can be **dropped** instead of imputing them.

### Explanation
- We removed the `deck` column because it has **more than 77% missing values**, making imputation less practical.  
- **Caution:** `df.drop()` does **not permanently remove** the column.  
- To permanently drop the column, use:  
```python
df.drop(columns=["deck"], inplace=True)
```
### Use for
- Drop columns with very high missing values to simplify the dataset and avoid unnecessary imputation.

---

## Handling Missing Values by Imputation

In [5]:
df["age"].fillna(df["age"].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

For columns with missing values, we can **fill them using statistical measures** like mean, median, or mode.  

### Explanation
- `df["age"].fillna(df["age"].median())` replaces all missing values in the `age` column with the **median age**.  
- Median is used instead of mean when the data may have **outliers**.  
- **Caution:** This does **not modify the original dataframe** unless you use `inplace=True` or assign it back:  
```python
df["age"] = df["age"].fillna(df["age"].median())
```

### Use for
- Use imputation to handle missing numerical values without losing data by dropping rows.
- Median is especially useful when the column has outliers.

---

## Handling Missing Categorical Values by Mode Imputation

In [6]:
df["embarked"].fillna(df["embarked"].mode()[0])

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: embarked, Length: 891, dtype: object

For categorical columns with missing values, we can **fill them using the most frequent value (mode)**.

### Explanation
- `df["embarked"].fillna(df["embarked"].mode()[0])` replaces all missing values in the `embarked` column with the **most frequent value**.  
- Mode imputation is suitable for **categorical columns**. General Use
Use mode imputation to handle missing categorical values without dropping rows.
Useful when the missing data is small and you want to preserve the dataset. 
- **Caution:** This does **not modify the original dataframe** unless you use `inplace=True` or assign it back:  
```python
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
```
### Use for
- Use mode imputation to handle missing categorical values without dropping rows.
- Useful when the missing data is small and you want to preserve the dataset.

---

## Handling Missing Values in Numerical Columns by Median Imputation

In [7]:
df["fare"].fillna(df["fare"].median())

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

 numerical columns with missing values, we can **fill them using median** to avoid losing data.

### Explanation
- `df["fare"].fillna(df["fare"].median())` replaces all missing values in the `fare` column with the **median fare**.  
- Median is preferred when the column may have **outliers**.  
- **Caution:** This does **not modify the original dataframe** unless you use `inplace=True` or assign it back:  
```python
df["fare"] = df["fare"].fillna(df["fare"].median())
```
### Use for
- Use median imputation to handle missing numerical values without dropping rows.
- Helps maintain dataset size and reduces bias caused by outliers.

---

## Handling Missing Values Using Forward Fill (ffill)

In [8]:
df.ffill()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,C,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,B,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True

Forward fill propagates the **last valid observation forward** to fill missing values.

### Explanation
- `df.ffill()` fills missing values by **carrying the previous row’s value forward**.  
- Useful when data is **ordered** (e.g., time series) and previous values are reasonable replacements.  
- **Caution:** This does **not modify the original dataframe** unless you use `inplace=True` or assign it back:  
```python
df = df.ffill()
```
### Use for
- Use forward fill to fill missing data sequentially, especially in time-dependent datasets.
- Helps preserve dataset size without dropping rows.

---

## Handling Missing Values Using Backward Fill (bfill)

In [9]:
df.bfill()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,26.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Backward fill fills missing values by **propagating the next valid observation backward**.

### Explanation
- `df.bfill()` fills missing values by **using the next row’s value**.  
- Useful when data is **ordered** and the next observation is a reasonable replacement.  
- **Caution:** This does **not modify the original dataframe** unless you use `inplace=True` or assign it back:  
```python
df = df.bfill()
```
### Use for
- Use backward fill to fill missing data sequentially from future values, especially in time-dependent datasets.
- Helps maintain dataset size without dropping rows.

---

## Handling Missing Values Using Machine Learning Model

In [10]:
from sklearn.ensemble import RandomForestRegressor

# Use only relevant features
age_df = df[["age", "pclass", "sibsp", "parch", "fare"]]

# Split into known and unknown
known_age = age_df[age_df["age"].notnull()]
unknown_age = age_df[age_df["age"].isnull()]

X_train = known_age.drop("age", axis=1)
y_train = known_age["age"]

X_test = unknown_age.drop("age", axis=1)

# Train model
model = RandomForestRegressor()
model.fit(X_train, y_train)

# Predict missing Age
predicted_ages = model.predict(X_test)

# Fill back
df.loc[df["age"].isnull(), "age"] = predicted_ages

df['age'].isnull().sum()

np.int64(0)

For numerical columns, missing values can be **predicted using a machine learning model** based on other related features.

### Explanation
- We use a `RandomForestRegressor` to predict missing `age` values using other features.  
- After prediction, all missing `age` values are filled (`df['age'].isnull().sum()` returns `0`).  
- Model-based imputation is more accurate than simple mean/median when other features correlate with the missing column.

### Use for
- Use machine learning-based imputation for **numerical columns with patterns related to other features**.  
- Ideal for datasets where missing data is significant but predictable using other columns.

---